/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Consultation } from "./Consultation";
import { ConsultationCountArgs } from "./ConsultationCountArgs";
import { ConsultationFindManyArgs } from "./ConsultationFindManyArgs";
import { ConsultationFindUniqueArgs } from "./ConsultationFindUniqueArgs";
import { CreateConsultationArgs } from "./CreateConsultationArgs";
import { UpdateConsultationArgs } from "./UpdateConsultationArgs";
import { DeleteConsultationArgs } from "./DeleteConsultationArgs";
import { LabRequestFindManyArgs } from "../../labRequest/base/LabRequestFindManyArgs";
import { LabRequest } from "../../labRequest/base/LabRequest";
import { Appointment } from "../../appointment/base/Appointment";
import { ConsultationService } from "../consultation.service";
@graphql.Resolver(() => Consultation)
export class ConsultationResolverBase {
  constructor(protected readonly service: ConsultationService) {}

  async _consultationsMeta(
    @graphql.Args() args: ConsultationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Consultation])
  async consultations(
    @graphql.Args() args: ConsultationFindManyArgs
  ): Promise<Consultation[]> {
    return this.service.consultations(args);
  }

  @graphql.Query(() => Consultation, { nullable: true })
  async consultation(
    @graphql.Args() args: ConsultationFindUniqueArgs
  ): Promise<Consultation | null> {
    const result = await this.service.consultation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Consultation)
  async createConsultation(
    @graphql.Args() args: CreateConsultationArgs
  ): Promise<Consultation> {
    return await this.service.createConsultation({
      ...args,
      data: {
        ...args.data,

        appointment: args.data.appointment
          ? {
              connect: args.data.appointment,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Consultation)
  async updateConsultation(
    @graphql.Args() args: UpdateConsultationArgs
  ): Promise<Consultation | null> {
    try {
      return await this.service.updateConsultation({
        ...args,
        data: {
          ...args.data,

          appointment: args.data.appointment
            ? {
                connect: args.data.appointment,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Consultation)
  async deleteConsultation(
    @graphql.Args() args: DeleteConsultationArgs
  ): Promise<Consultation | null> {
    try {
      return await this.service.deleteConsultation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [LabRequest], { name: "labRequests" })
  async findLabRequests(
    @graphql.Parent() parent: Consultation,
    @graphql.Args() args: LabRequestFindManyArgs
  ): Promise<LabRequest[]> {
    const results = await this.service.findLabRequests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Appointment, {
    nullable: true,
    name: "appointment",
  })
  async getAppointment(
    @graphql.Parent() parent: Consultation
  ): Promise<Appointment | null> {
    const result = await this.service.getAppointment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
