/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ConsultationWhereUniqueInput } from "../../consultation/base/ConsultationWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { LabReportListRelationFilter } from "../../labReport/base/LabReportListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

@InputType()
class LabRequestWhereInput {
  @ApiProperty({
    required: false,
    type: () => ConsultationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ConsultationWhereUniqueInput)
  @IsOptional()
  @Field(() => ConsultationWhereUniqueInput, {
    nullable: true,
  })
  consultation?: ConsultationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  instructions?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  labName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LabReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LabReportListRelationFilter)
  @IsOptional()
  @Field(() => LabReportListRelationFilter, {
    nullable: true,
  })
  labReports?: LabReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  requestDate?: DateTimeNullableFilter;
}

export { LabRequestWhereInput as LabRequestWhereInput };
